reporting: "off"
colors:
   selectedLineBgColor:
      - reverse
   selectedRangeBgColor:
      - reverse
    # activeBorderColor:
    # - green
    # - bold
    # inactiveBorderColor:
    # - white
    # optionsTextColor:
    # - blue
