variables:
    postgres_connection: psql postgres --no-align --tuples-only
runcharts:
  - title: Search engine response time
    position: [[0, 0], [45, 19]]
    rate-ms: 5000
    legend:
        enabled: true
        details: false
    scale: 2
    items:
      - label: GOOGLE
        color: 178
        sample: curl -o /dev/null -s -w '%{time_total}'  https://www.google.com
      - label: YAHOO
        sample: curl -o /dev/null -s -w '%{time_total}'  https://search.yahoo.com
      - label: BING
        sample: curl -o /dev/null -s -w '%{time_total}'  https://www.bing.com
barcharts:
  - title: Local network activity
    position: [[45, 11], [35, 8]]
    rate-ms: 1500
    scale: 0
    items:
      - label: UDP bytes in
        sample: nettop -J bytes_in -l 1 -m udp | awk '{sum += $4} END {print sum}'
      - label: UDP bytes out
        sample: nettop -J bytes_out -l 1 -m udp | awk '{sum += $4} END {print sum}'
      - label: TCP bytes in
        sample: nettop -J bytes_in -l 1 -m tcp | awk '{sum += $4} END {print sum}'
      - label: TCP bytes out
        sample: nettop -J bytes_out -l 1 -m tcp | awk '{sum += $4} END {print sum}'
gauges:
  - title: YEAR PROGRESS
    position: [[45, 0], [35, 2]]
    cur:
        sample: date +%j
    max:
        sample: echo 365
    min:
        sample: echo 0
  - title: DAY PROGRESS
    position: [[45, 3], [35, 2]]
    cur:
        sample: date +%H
    max:
        sample: echo 24
    min:
        sample: echo 0
sparklines:
  - title: PostgreSQL
    position: [[0, 28], [45, 12]]
    rate-ms: 1500
    init: $postgres_connection
    sample: select count(*) from pg_stat_activity;
textboxes:
  - title: Local weather
    position: [[55, 20], [25, 8]]
    rate-ms: 10000
    sample: curl wttr.in?0ATQF
    border: false
  - title: Paris weather
    position: [[55, 30], [25, 10]]
    rate-ms: 10000
    sample: curl wttr.in/paris?0ATQF
    transform: echo 1
    border: false
asciiboxes:
  - title: UTC time
    position: [[5, 20], [35, 7]]
    rate-ms: 1000
    sample: env TZ=UTC date +%r
    border: false
    font: 2d
