gui:
  mouseEvents: false
  showFileTree: false
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
  commitLength:
    show: true
git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"

reporting: "off"
disableStartupPopups: true

services:
  'gitlab.trobz.com': 'gitlab:gitlab.trobz.com'
