gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
    commitLength:
      show: true
    mouseEvents: false
    showFileTree: false
git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"

reporting: "off"
disableStartupPopups: true

services:
  'gitlab.trobz.com': 'gitlab:gitlab.trobz.com'
