#!/usr/bin/env bash

BG=0xFF2a2f38
FG=0xFFe1e3e4

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
ITEM_DIR="$HOME/.config/sketchybar/items"
FONT="RobotoMono Nerd Font"

# Bar
sketchybar -m --bar  \
  position=top       \
  height=35          \
  margin=4           \
  y_offset=-7        \
  corner_radius=10   \
  border_width=0     \
  border_color=$BG   \
  blur_radius=0      \
  padding_left=16    \
  padding_right=16   \
  color=$BG          \
  display=all        \
  hidden=off         \
  topmost=off        \
  font_smoothing=off \
  shadow=off

# Global defaults
sketchybar -m --default \
  updates=when_shown    \
  drawing=on            \
  cache_scripts=on

# Label Defaults
sketchybar -m --default                    \
  label.font="Helvetica Neue:Bold:13.0" \
  label.color=$FG                          \
  label.highlight_color=$FG                \
  label.padding_left=4                     \
  label.padding_right=4                    \
  label.y_offset=-2

# Icon Defaults
sketchybar -m --default                   \
  icon.font="$FONT:Bold:13.0" \

# Background Defaults
sketchybar -m --default       \
  background.height=32        \
  background.border_color=$BG \
  background.border_width=0   \
  background.corner_radius=0  \
  background.color=$BG        \
  background.drawing=off

# Spaces
# DISPLAY_1=(one two three four)
# DISPLAY_2=(five six)

# args=()

# create_display() {
#   arr=("$@")
#   for i in "${arr[@]}";
#   do

#       for i in "${!arr[@]}"; do
#           if [[ "${arr[$i]}" = "" ]]; then
#               echo "${i}";
#           fi
#       done
#     echo "$i"
#     args+=(--add space "$i" left                    \
#            --set "$i" associated_space=1            \
#            associated_display=1                    \
#            icon=                                  \
#            icon.highlight_color=0xff88c0d0         \
#            click_script="yabai -m space --focus 1" \
#        )
#   done
# }
# create_display "${DISPLAY_1[@]}"
# create_display "${DISPLAY_2[@]}"

sketchybar -m --default                     \
  icon.padding_left=4                       \
  icon.padding_right=4                      \
  icon.y_offset=-2                          \
  --add space one left                      \
  --set one associated_space=1              \
    associated_display=1                    \
    icon=                                  \
    icon.highlight_color=0xff88c0d0         \
    click_script="yabai -m space --focus 1" \
  --add space two left                      \
  --set two associated_display=1            \
    associated_space=2                      \
    icon=                                  \
    icon.highlight_color=0xff88c0d0         \
    click_script="yabai -m space --focus 2" \
  --add space three left                    \
  --set three associated_display=1          \
    associated_space=3                      \
    icon=                                  \
    icon.highlight_color=0xff88c0d0         \
    click_script="yabai -m space --focus 3" \
  --add space four left                     \
  --set four associated_display=1           \
    associated_space=4                      \
    icon=                                  \
    icon.highlight_color=0xff88c0d0         \
    click_script="yabai -m space --focus 4" \
    \
    --add space five left                     \
    --set five associated_display=2           \
    associated_space=5                      \
    icon=                                  \
    icon.highlight_color=0xff88c0d0         \
    click_script="yabai -m space --focus 5" \
    \
    --add space six left                     \
    --set six associated_display=2           \
    associated_space=6                      \
    icon=                                  \
    icon.highlight_color=0xff88c0d0         \
    click_script="yabai -m space --focus 6" \

source "$ITEM_DIR/github.sh"
source "$ITEM_DIR/network.sh"

# Right Items
sketchybar -m --default          \
  label.padding_left=0           \
  label.padding_right=0          \
  icon.padding_left=20           \
  icon.padding_right=8           \
  icon.y_offset=-2               \
  --add item clock right         \
  --set clock                    \
    update_freq=10               \
    script="$PLUGIN_DIR/clock.sh"   \
    icon=                       \
    icon.y_offset=-2             \
    icon.color=0xff8fbcbb        \
  --add item date right          \
  --set date                     \
    update_freq=100              \
    script="$PLUGIN_DIR/date.sh"    \
    icon=                       \
    icon.y_offset=-2             \
    icon.color=0xffb48ead        \
  --add item battery right       \
  --set battery                  \
    update_freq=10                \
    script="$PLUGIN_DIR/power.sh"   \
    icon=                       \
    icon.color=0xffbf616a        \
  --add item sound right         \
  --set sound                    \
    update_freq=5                \
    icon.color=0xff5e81ac        \
    script="$PLUGIN_DIR/sound.sh"   \
  --add item weather right       \
  --set weather                  \
    update_freq=7200             \
    icon.color=0xffebcb8b        \
    script="$PLUGIN_DIR/weather.sh" \
  # --add item mailIndicator right \
  # --set mailIndicator            \
  #   update_freq=7200               \
  #   icon.color=0xff5e81ac        \
  #   script="$PLUGIN_DIR/mail.sh"    \
  #   click_script="osascript -e 'tell application \"Mail\" to activate'"

# Center Items
sketchybar -m --add event window_focus \
              --add event title_change

sketchybar -m --add item title center                \
    --set title script="$PLUGIN_DIR/window_title.sh" \
    label.padding_right=30                           \
    --subscribe                                      \
    title window_focus front_app_switched space_change

sketchybar -m --update && echo "sketchybar configuration loaded.."
